"""add tower and update bookings

Revision ID: 872dbb4396a8
Revises: 
Create Date: 2026-01-23 15:53:29.686275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872dbb4396a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active_tenant', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tower_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'towers', ['tower_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tower_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('is_active_tenant')

    # ### end Alembic commands ###
